# Generated by Django 3.0.7 on 2020-06-29 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObstSorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obst_sorte', models.CharField(max_length=64)),
                ('reifezeit', models.CharField(max_length=30)),
                ('verwendung', models.CharField(max_length=248)),
                ('geschmack', models.CharField(max_length=248)),
                ('lagerfaehigkeit', models.CharField(max_length=248)),
                ('alergie_info', models.CharField(max_length=248)),
                ('www', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), size=5)),
                ('bilder', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=20)),
            ],
        ),
    ]
