version: '3.7'

services:

  dpostgres:
    # Bau das Image aus dem lokalen Dockerfile
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - pg.env
    volumes:
      - /home/uws/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

  hilgi:
    image: hilgi:0.9.2.2
    env_file:
      - hilgi.env
    ports:
      - "8002:8000"
    restart: unless-stopped
