# Generated by Django 3.0.7 on 2020-06-29 15:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obstsorten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiese',
            fields=[
                ('wiesen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('bilder', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='uploads/Wiese'), blank=True, size=20)),
            ],
        ),
        migrations.AlterField(
            model_name='obstsorten',
            name='bilder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='uploads/Sorte'), blank=True, size=20),
        ),
        migrations.CreateModel(
            name='ObstBaum',
            fields=[
                ('baum_id', models.AutoField(primary_key=True, serialize=False)),
                ('bilder', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='uploads/Wiese'), blank=True, size=20)),
                ('obst_sorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstsorten.ObstSorten')),
                ('wiese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstsorten.Wiese')),
            ],
        ),
    ]
