# Generated by Django 3.0.7 on 2020-06-29 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstsorten', '0002_auto_20200629_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiese',
            name='bluehwiese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wiese',
            name='grafik',
            field=models.ImageField(default=None, upload_to='uploads/Wiese'),
        ),
        migrations.AddField(
            model_name='wiese',
            name='obstwiese',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='obstbaum',
            name='bilder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='uploads/Wiese'), blank=True, size=20),
        ),
        migrations.AlterField(
            model_name='obstsorten',
            name='bilder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='uploads/Sorte'), blank=True, size=20),
        ),
        migrations.AlterField(
            model_name='wiese',
            name='bilder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='uploads/Wiese'), blank=True, size=20),
        ),
    ]
