# Generated by Django 3.0.7 on 2020-06-30 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstsorten', '0003_auto_20200629_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstsorten',
            old_name='reifezeit',
            new_name='genuss_reif',
        ),
        migrations.AddField(
            model_name='obstbaum',
            name='letzter_schnitt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='obstbaum',
            name='zustand',
            field=models.CharField(blank=True, max_length=248),
        ),
        migrations.AddField(
            model_name='obstsorten',
            name='pflueck_reif',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obstsorten',
            name='www',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=128), size=5),
        ),
    ]
