# Generated by Django 3.0.7 on 2020-06-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstsorten', '0004_auto_20200630_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstsorten',
            name='genuss_reif',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
