# Generated by Django 3.0.7 on 2020-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstsorten', '0005_auto_20200630_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstsorten',
            name='obst_sorte',
            field=models.CharField(help_text='Obstsorte: Name der Obstsorte. z.B. rheinischer Winterrambour', max_length=64),
        ),
    ]
